name: reaprime
description: "Reasonable Espresso App"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  logging: ^1.3.0
  logging_appenders: ^1.3.1
  flutter_foreground_task: 9.2.0
  permission_handler: ^12.0.0+1
  rxdart: ^0.28.0
  shelf: ^1.0.0
  battery_plus: ^7.0.0
  collection: ^1.19.0
  shelf_plus: ^1.10.0
  shadcn_ui: ^0.36.1
  file_picker: ^10.3.8
  fl_chart: ^1.0.0
  flutter_launcher_icons: ^0.14.3
  uuid: ^4.5.1
  path_provider: ^2.1.5
  archive: ^3.6.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  shelf_static: ^1.1.3
  path: ^1.9.1
  shelf_cors_headers: ^0.1.5
  url_launcher: ^6.3.2
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  ansi_escape_codes: ^2.1.0
  flutter_js:
    git:
      url: https://github.com/tadelv/dart_js
      ref: master
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  firebase_performance: ^0.11.1+3
  firebase_analytics: ^12.1.0
  http: ^1.2.2
  network_info_plus: ^7.0.0
  window_manager: ^0.5.1
  web_socket_channel: ^3.0.0
  bonsoir: ^5.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.10.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/web/
    - assets/plugins/time-to-ready.reaplugin/
    - assets/plugins/visualizer.reaplugin/
    - assets/plugins/settings.reaplugin/
    - assets/defaultProfiles/
